### ISSUE TITLE
 Screen sharing doesn't work anymore in telegram and kotatogram flatpaks

### ISSUE THREAD

**Issue by pizzadude** [flathub/io.github.kotatogram#21]
I don't know when this stopped working, but in Fedora 35 KDE Wayland session, the Telegram (and Kotatogram) flatpaks don't let me screen share. It works fine in the RPM version of Telegram from RPMFusion though. When I select screen share in the kotatogram and telegram flatpaks, the portal permission popup shows up, I grant permission, but nothing happens. Any ideas?

System info:
Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.14-200.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7300U CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by ilya-fedin** [comment]
Hi, again

**Comment by pizzadude** [comment]
Hi.

**Comment by ilya-fedin** [comment]
Closing sue to inactivity in https://github.com/flathub/org.telegram.desktop/issues/371
